/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package cn.dayutianfei.loadserver.lib.avro.protocol;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Status { 
  OK, FAILED, UNKNOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Status\",\"namespace\":\"cn.dayutianfei.loadserver.lib.avro.protocol\",\"symbols\":[\"OK\",\"FAILED\",\"UNKNOWN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
